version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: directus_global
      MYSQL_USER: cmsuser
      MYSQL_PASSWORD: cmspass123
      MYSQL_ROOT_PASSWORD: cmspass123

  directus:
    image: directus/directus:latest
    depends_on:
      - mysql
    environment:
      KEY: testsecret
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: admin123
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: directus_global
      DATABASE_USER: cmsuser
      DATABASE_PASSWORD: cmspass123
